idf_component_register(
    SRCS 
        "src/midi_sync.c"
        "src/midi_in.c"
        "src/midi_out.c"
        "src/analog_sync.c"
        "src/ableton_link.c"
    INCLUDE_DIRS 
        "include"
    PRIV_REQUIRES 
        driver
        esp_timer
        freertos
        esp_wifi
        esp_netif
        lwip
)
