[pytest]
testpaths = host_tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --embedded-services=esp,idf
    --embedded-services-args=esp.port=/dev/cu.usbmodem*
    -v
    --tb=short

